// This file is generated by Firebase Extensions.
'use server';

// As variáveis de ambiente agora são carregadas no AuthProvider
// para garantir que estejam disponíveis em todo o ciclo de vida da aplicação.

/**
 * @fileOverview This file is the entrypoint for Genkit's developer UI.
 *
 * It is not included in production builds.
 */
import {getFlows} from 'genkit';
// @ts-ignore
import * as flow from './flows/*';
export const f = getFlows(flow);
