<<<<<<< HEAD

// This file is generated by Firebase Extensions.
'use server';

/**
 * @fileOverview This file is the entrypoint for Genkit's developer UI.
 *
 * It is not included in production builds.
 */
import {getFlows} from 'genkit';
// @ts-ignore
import * as flow from './flows/*';
export const f = getFlows(flow);
=======
// Flows will be imported for their side effects in this file.
import "./flows/extract-equipment-details-flow";
import "./flows/extract-connection-details-flow";
import "./flows/import-spreadsheet-flow";
import "./flows/developer-tools-flow";
import "./flows/learning-machine-flow";
>>>>>>> d3ee8b12c20e0454b2def011137783add0a5af09
